### ISSUE TITLE
 Nearby.CONNECTIONS_API is not available on this device.

### ISSUE THREAD

**Issue by wanghang199112** [googlesamples/android-nearby#51]
When I use "compile com.google.android.gms:play-services-nearby:11.8.0" and use Nearby.getConnectionsClient() to advertise or discover，I meet blow problem，how can I resolve it?
Thank you very much!

1 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err: com.google.android.gms.common.api.ApiException: 17: API: Nearby.CONNECTIONS_API is not available on this device.
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.api.internal.zzb.zzs(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.api.internal.zzd.zzs(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.api.internal.zzbo.zzw(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.api.internal.zzbo.onConnectionFailed(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.internal.zzad.onConnectionFailed(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.internal.zzn.zzj(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.internal.zze.zzw(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.internal.zzi.zzaks(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at android.os.Looper.loop(Looper.java:148)
02-11 19:55:17.871 27502-27502/com.dewmobile.kuaiya.neartrans W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by wanghang199112** [comment]
If use Nearby.getConnectionsClient()  instead of Nearby.Connections，don't init GoogleApiClient and invoke connect().
